### ISSUE TITLE
Thunk support

### ISSUE THREAD

**Issue by lostincomputer** [ioof-holdings/redux-dynostore#160]
Is Redux Thunk supported?

I configured my store to

import { createStore } from "redux";
import { rootReducer } from "./reducers";
import { composeWithDevTools } from "redux-devtools-extension";
import dynostore, { dynamicReducers } from "@redux-dynostore/core";
import thunk from "redux-thunk";
import { applyMiddleware } from "redux-subspace";

export const store = createStore(
  rootReducer,
  composeWithDevTools(dynostore(dynamicReducers()), applyMiddleware(thunk))
)

but my thunk doesn't get executed.

**Comment by mpeyper** [comment]
Yes, thunks are supported.

The store setup looks fine so I'll need to see the thunk and how you're dispatching it to help you out any further.

I'm on holidays at the moment, so my response times might be a bit slow.

**Comment by lostincomputer** [comment]
The action is bare-bone

export function thunkTest() {
  return async (dispatch) {
    console.log("thunkTest");
  };
}

Works when I dispatch it on a React component that's on the root but it doesn't work when I dispatch it on a component that is on a subspace. Here is the component:

export const Spreadsheet = props => {
  const ConnectedSpreadsheet = dynamic(
    props.identifier,
    subspaced(),
    attachReducer(spreadsheetReducer)
  )(UnconnectedSpreadsheet);

  return <ConnectedSpreadsheet {...props} />;
};

I'm using the useDispatch hook to dispatch the action it both cases

 const dispatch = useDispatch();
 dispatch(thunkTest());

Non-thunk action works in the subspace.

Sidenote: What I'm doing is experimenting with having complex components use Redux.  Spreadsheet in this case is a simple spreadsheet editor.

Thanks for your help!

**Comment by lostincomputer** [comment]
I tested it again and it works now for some reason. I spent an hour trying to fix it yesterday and thought that it had something to do with your library. Sorry for wasting your time.

**Comment by mpeyper** [comment]
Ha, no worries.

I have to mention one thing though:

```js
export const Spreadsheet = props => {
  const ConnectedSpreadsheet = dynamic(
    props.identifier,
    subspaced(),
    attachReducer(spreadsheetReducer)
  )(UnconnectedSpreadsheet);

  return <ConnectedSpreadsheet {...props} />;
};
```

There is an issue with this snippet.  `dynamic` creates a higher-order component, which you shouldn't do as part of rendering.  See [this article on the react docs](https://reactjs.org/docs/higher-order-components.html#dont-use-hocs-inside-the-render-method) for more details.

For basic use cases, you can us the [`createInstance` function](https://github.com/ioof-holdings/redux-dynostore/tree/master/packages/redux-dynostore-react-redux#multiple-instances) to change the identifier for multiple instances, but you do need to know what they identifiers are going to be.

I've seen cases where `useMemo` to dynamically change the identifier and only recreate the component when the identifier changes, and we've [had discussions before](https://github.com/ioof-holdings/redux-dynostore/issues/10#issuecomment-398645882) about accepting `identifier` as a prop instead of having to statically assign them, but nothing has ever come of it.
