### ISSUE TITLE
Mix redux-persist and redux-dynostore

### ISSUE THREAD

**Issue by namnguyen2091** [ioof-holdings/redux-dynostore#216]
I can mix two library by following code, but when dynamic reducer is created I can not see it in storage. How do I fix it?

Here is repository of redux-persist: https://github.com/rt2zz/redux-persist. I try to get mapState but it's not working too and everythings I created in static reducer is undefined in this.props.

```
import {store} from "../../helpers";
const value = store.getKeys('ABC');
```

```
import { createStore, compose } from 'redux';
import thunkMiddleware from 'redux-thunk';
import { createLogger } from 'redux-logger';
import rootReducer from '../reducers';

import { persistStore, persistReducer } from 'redux-persist'
import storage from 'redux-persist/lib/storage' // defaults to localStorage for web
import autoMergeLevel2 from 'redux-persist/lib/stateReconciler/autoMergeLevel2';
import dynostore, { dynamicReducers } from '@redux-dynostore/core'
import { applyMiddleware } from 'redux-subspace'

const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose

const persistConfig = {
	key: 'root',
	storage,
	stateReconciler: autoMergeLevel2
}
const persistedReducer = persistReducer(persistConfig, rootReducer)

const loggerMiddleware = createLogger();

const store = createStore(
       persistedReducer,
	composeEnhancers(applyMiddleware(thunkMiddleware, loggerMiddleware), dynostore(dynamicReducers()))
);


const persistor = persistStore(store);

store.subscribe(() => {
	// do something in here
});

export {store, persistor};
```
And in my component I call, it runs without error:

```
class Task extends React.Component {}

const mapStateToProps = state => {
    return {
        projects: state.projects,
        status: state.taskstatus,
    }
}

const mapDispatchToProps = dispatch => {
    return {
        loadProject: (value) => dispatch({
            type: 'LOAD_PROJECT',
            value: value
        }),
        loadStatus: (value) => dispatch({
            type: 'LOAD_TASK_STATUS',
            value: value
        }),
    }
}

const X = dynamic('ABC', attachReducer(projectsReducer), subspaced())(Task)
const Y = connect(
  mapStateToProps,
  mapDispatchToProps
)(X);
export {Y as TaskPage}
```

**Comment by mpeyper** [comment]
Just to clarify, do you have two seperate issues?

1. the dynamic reducers are not present in the storage
2. the root reducer values are not available in the `Task` `mapStateToProps` function

Is that correct?

The issue with 1 is that the static and dynamic reducers are very much seperate in the core of dynostore.  If you want dynamic reducers to be persisted, you will need to wrap them in their own `persistReducer` call with a different key, before passing them to `attachReducers`.  To be honest, I'm not sure how this will behave when rehydrating the state again when the store is being created and the dynamic reducers have not been attached yet.  My guess is it won't work, but there is little we can do about it as we don't know which reducers will be attached in the future or when.

The issue with 2 is that you `Task` is using the `subspaced` enhancer, so it's scoping the state to just that of the attached reducer (`projectsReducer`).  You would need to look at the `redux-subspace-wormhole` middleware in order to make those root level values available to the subspaces, e.g.

```js
const store = createStore(
       persistedReducer,
	composeEnhancers(
          applyMiddleware(thunkMiddleware, loggerMiddleware, wormhole('taskstatus'),
          dynostore(dynamicReducers()))
);
```

**Comment by namnguyen2091** [comment]
Thanks, this is correct. I think there are too much problem to mix both package, so I will try the last once and then I'm sorry, I will remove this package.
