### ISSUE TITLE
Cannot re-add sagas after they have been removed [redux-saga]

### ISSUE THREAD

**Issue by irosner** [ioof-holdings/redux-dynostore#229]
### Is it a bug, feature request or question?
Bug

### Input Code

```js
const store = createStore(
  rootReducer,
  compose(
    applyMiddleware(sagaMiddleware),
    dynostore(dynamicReducers(), dynamicSagas(sagaMiddleware)),
  )
);

function* userSagas() {}

const module = {
  name: users,
  sagas: userSagas
};

// run saga first time - works great
store.runSagas({ [module.name]: module.sagas });

// Module unmounted - other module loaded 
// ...
store.cancelSagas([module.name]);

// remount module
// ...
// Does nothing
store.runSagas({ [module.name]: module.sagas });
```

### Expected Behavior

Sagas will start working again after they are re-attached
This is described in original PR description - https://github.com/ioof-holdings/redux-dynostore/pull/16
>I have ensured that replacement reducers / sagas with can be re-added after they are removed.

### Current Behavior

Nothing happens

### Possible Solution
Seems connected to changes in redux-saga 1.0
https://github.com/redux-saga/redux-saga/issues/1743#issuecomment-457980445
https://github.com/bmealhouse/next-redux-saga/issues/27#issuecomment-458662336

### Context
We am using redux-dynostore as part of a large project where every page is a separate npm package and dynamically loaded. It is being used in production.
Some modules are generic(GenericModule) and can be configured by passing props from  main app layer(ModuleA, ModuleB). So action names stay the same etc. We discovered some bugs with this - i.e. if ModuleA is loaded, then ModuleB is loaded and  fires action - sagas are fired both in ModuleA + ModuleB.
So when unmounting ModuleA, we need to ensure that sagas stop listening.
Then when remounting ModuleA restart sags.
Issue is that sagas don't restart after they have been cancelled

### Your Setup

| package         | version(s)
| --------------- | ----------
| redux-saga           |  1.1.3
| redux-dynostore | 3.0.1
| etc.            |

**Comment by mpeyper** [comment]
Hi @irosner,

Thanks for your patience in waiting for a response.  I'm not sure what the path forward is here for us as the way we run and cancel sagas is a [thin layer over the saga middleware](https://github.com/ioof-holdings/redux-dynostore/blob/master/packages/redux-dynostore-redux-saga/src/dynamicSagas.js#L14-L29).  I've read through those issues but I'll be honest that I'm not sure how we're supposed to be doing it so that starting the saga works again.   Happy for any input from someone with more experience with sagas.

I haven't tried it, but I wonder if wrapping the saga in new saga that just yields to the passed saga would allow it to run each time?  Just a thought.

I'll try to find some time to look at this soon, but am quite busy in my day job at the moment so I won't make any promises of a quick turn around.

**Comment by mpeyper** [comment]
Closing. Please see #484 for details.
