### ISSUE TITLE
Upgrade to React 16.13.1 creates a new console warning

### ISSUE THREAD

**Issue by Ethorsen** [ioof-holdings/redux-dynostore#234]
Hi guys,

Hope you're doing well.

React 16.13.x introduces a new warning 

https://github.com/facebook/react/blob/master/CHANGELOG.md#react-dom-1
- Warn when a function component is updated during another component's render phase (@acdlite in #17099)

As soon as we update, we have this warning thrown, something like described here

- https://github.com/facebook/react/issues/18178#issuecomment-596266655

Warning can be seen easily through one of your example (maybe other examples too)

- https://codesandbox.io/s/github/ioof-holdings/redux-dynostore/tree/master/examples/real-world

> Warning: Cannot update a component (`ConnectFunction`) while rendering a different component (`Dynamic(Connect(App))`). To locate the bad setState() call inside `Dynamic(Connect(App))`, follow the stack trace as described in https://fb.me/setstate-in-render
>     in Dynamic(Connect(App)) (at Routes.js:11)
>     in LoadableComponent (at Routes.js:30)
>     in Route (at Routes.js:27)
>     in Routes (at Root.dev.js:12)
>     in Router (created by ConnectedRouter)
>     in ConnectedRouter (created by Context.Consumer)
>     in ConnectedRouterWithContext (created by ConnectFunction)
>     in ConnectFunction (at Root.dev.js:11)
>     in div (at Root.dev.js:10)
>     in Provider (at Root.dev.js:9)
>     in Root (at src/index.js:9)

**Comment by mpeyper** [comment]
Thanks, I'll look into it.

**Comment by Ethorsen** [comment]
Hi @mpeyper,   have you had a chance to look into this?  

React 17 is coming up and most likely the console warning will persist.   

Thx

**Comment by mpeyper** [comment]
Sorry @Ethorsen I haven't. Covid happened and my time for OSS has all but evaporated (home schooling kids plus my day job) and I forgot about it.

Thanks for reminding me and I'll try to look into it soon 😅

If anyone else has the capacity, I'll gladly accept PRs for this.

**Comment by mpeyper** [comment]
I'm just really confused by this.  The error says there is a "bad setState() call inside Dynamic(Connect(App))", but we don't have a single `setState` call (class component or hook) in the entire repo (including examples).

Is it possible it's another dependency that is causing it, but because we're wrapping it in out HOC it is reporting like it's coming from us? I'm not trying to handball it, but I'm genuinely not sure where the warning is coming from at this point.

**Comment by Ethorsen** [comment]
I believe it is really confusing for everybody.  It is very possible that the warning is coming from one of the deps.

Upgrading to React 17 rc0 still prints the warning, but in a new format.  Might give a different perspective on the issue.
https://codesandbox.io/s/magical-lamport-7yh3g

Maybe its coming from react-loadable,  I dunno.

**Comment by mpeyper** [comment]
I think I might have cracked it.  the `attachReducer` enhancer, when used with `dynamic` ends up calling `store.replaceReducer` in the render path which I think is producing the warning (presumable the other connected components are checking if their state is affected by the updated state or something, which is why the warning mentions `ConnectFunction`).

I've got a very hacky version that runs the `real-world` app without the warning, but there are a few build in assumption to make it work.  The main change is the `attachReducer` call is pushed into `useEffect` instead of called in the render path, but this mean the first time the wrapped components render, the reducer has not actually been attached yet.

To get around that, the component renders `null` on the first render before rendering properly on after the effect has triggered.  I _think_ this is an ok assumption, but I'm sure I'll see issue from it at some point.

The other complication is that because it uses `useEffect` it needs `react` as a dependency, this meant creating an overload of `attachReducers` in `@redux-dynostore/react-redux` and `@redux-dynostore/react-redux-subspace` (for the non-subspaced and subspaced use cases, respectively).  That's now 4 variations of effectively the same enhancer.  The `react-redux-subspace` can either wrap the `redux-subspace` implementation to add the effect logic, or the `redux-subspace` to add the subspacing logic, but not both (at least I can't figure out a way to do both), so I'm duplicating something somewhere.  I just need to figure out which duplication is going to cause the least issues (both for bundle size and maintainability).

It's late here now, so I'll clean this tomorrow or the weekend and try to get a fix out for next week.  Let me know if any of the above concerns you or if you have any clever ideas now that (I think) we know what the issue is.

**Comment by mpeyper** [comment]
I managed to find a (obvious in hindsight) way to not need to introduce new variations of `attachReducer`, but rather move when the enhancer chains are executed in `dynamic` itself.  This made it a much cleaner change to make, but the same assumptions about rendering `null` for a single render is still there.

The PR is up #347 and I'm considering publishing an alpha build to see if we can validate in some actual projects if it fixes the warning or if the above assumption causes any issues in practise.  @Ethorsen (or anyone else), let me know if you're interested in this and I'll push something out.

**Comment by Ethorsen** [comment]
We'll gladly test if there is a released alpha.  I'll try to schedule it in the next few weeks.

**Comment by mpeyper** [comment]
@Ethorsen done.  All packages have been published as alpha version `3.1.1-alpha.0`.  Give it a run and let me know how it goes.
