### ISSUE TITLE
ImmutableJs support [@redux-dynostore/core]

### ISSUE THREAD

**Issue by mpeyper** [ioof-holdings/redux-dynostore#4]
### Is it a bug, feature request or question?

Feature request

### Which package(s) does this involve?

@redux-dynostore/core

### Input Code

This issue is duplicating ioof-holdings/redux-dynamic-reducer#9 from the old library.

@kovcic asked:

> I have entire state as immutable.js object. From what I have seen this lib doesn't support that case. Correct me if I'm wrong or share a tip if possible to use it that way. Thx

### Expected Behavior

The redux state can be an immutablejs object and work with redux-dynostore

### Current Behavior

I replied:

> From memory, Redux's combineReducers function does not work with the immutablejs structures, so that is likely the main reason preventing it from working (and all the other ways we merge and wrap the reducers).

### Possible Solution

Allow the combine and merge reducer functions to be injected in (defaulting to the current functions) so that some immutablejs supported versions can be supplied.

You might want to start [here](https://github.com/ioof-holdings/redux-dynostore/blob/master/packages/redux-dynostore-core/src/createDynamicReducer.js#L9,L10)

See https://github.com/gajus/redux-immutable for a `combineReducers` replacement.

**Comment by TomiS** [comment]
Hey. I made a first attempt on this. I managed to get my page loading without errors with these changes to the library:
https://github.com/TomiS/redux-dynostore/commit/2dafdec3b66b6610eaa6579d865f8a291dd1992d
It seems `filteredReducer.js` requires most of the changes because the original implementation assumes plain javascript object as state. `createDynamicReducer.js`, however, can be handled by providing combineReducers and merger as you suggested. (I just overwrote them in this first implementation though)

I just quickly tested this by replacing one reducer slice in our application and it seemed to work, but haven't done any more exhaustive testing yet. I just wanted to share this asap to get discussion started.

**Comment by mpeyper** [comment]
Hey @TomiS,

Thanks for having a go at this.  I think you're on a good track.  I definitely agree that allowing `combineReducers` (and probably `concatenateReducers`) to be be overridden is the way to go here.

The bit I'm not sure of is how we can allow both the default and immutablejs implementations to co-exist, unless we also allow a custom `filteredReducer` function as well, which feels a bit odd.  

Interestingly, the only reason `filteredReducer` exists is because of a [warning produced by the default `combineReducers` function](https://github.com/reduxjs/redux/issues/2427) and a [fair bit of effort](https://stackoverflow.com/questions/43290107/combine-redux-reducers-without-adding-nesting) was put into working around it.  

In theory, if we provided our own `combineReducers` implementation for the default case (or found another one somewhere else in the ecosystem) that didn't produce the warning, then we might be able to throw the whole file away.

**Comment by jpeyper** [comment]
Will the changes in #18 effectively close this issue?

**Comment by mpeyper** [comment]
Yes
