### ISSUE TITLE
Docs and use cases?

### ISSUE THREAD

**Issue by markerikson** [ioof-holdings/redux-dynostore#5]
Skimming through the READMEs, this looks very interesting.  Can you clarify how this relates to `redux-subspace` and `redux-dynamic-reducer`?  Is it a superset, a wrapper, or something else?

**Comment by mpeyper** [comment]
It is a replacement for `redux-dynamic-reducer` (I'll be adding deprecation warnings those packages soon).

There is an interesting relationship with `redux-subspace`.  It does not require it to do it's thing (if you just want to dynamically attach reducers or run sagas, then you can, but it has been designed to work very well and closely with subspace so that a component ("micro-frontend") can wire everything together and function independently when when it mounts.  

Likewise, the React bindings is just one way to use the dynamic features (it's the only one that we support right now though). There is no reason that someone couldn't write binding for another view framework, or for other use cases (e.g. we speculated with a `dynamic` wrapper for sagas that would attach a reducer when a saga is run).

We primarily use it with code-splitting so that everything involved with a micro-frontend can be in a seperate bundle to the main application and only introduced into the app if it actually appears in the component tree (i.e. if you never visit a page on the app, the associated reducers, sagas, etc. are not executed.

I'm curious how you stumbled across this one (I haven't started promoting it in any way yet).

**Comment by mpeyper** [comment]
The docs here are still more or less what we had on the internal repo, so there are likely some mistakes and assumptions of knowledge and should be improved.

**Comment by jennguyen54** [comment]
@mpeyper I'm a big fan of the library. I have been playing around with redux-dynamic-reducer and this one for a few weeks so I'll be happy to help with the documentation and some "recipes" for some common use cases if needed  :D

**Comment by mpeyper** [comment]
More than happy to see them. 

What use cases did you have in mind?

**Comment by burakakca** [comment]
Any progress on the redux-dynostore document?

**Comment by mpeyper** [comment]
Sorry no.  Just what's in the [READMEs](https://github.com/ioof-holdings/redux-dynostore#packages).

**Comment by mpeyper** [comment]
Closing. Please see #484 for details.
